-- Schema for per-user message ordering and exclusivity.
-- Applied at startup by SchemaInitializer under an advisory lock (R-007).
-- Every statement is idempotent so that starting an instance against an existing
-- database is a no-op rather than an error.

CREATE TABLE IF NOT EXISTS messages (
    id             uuid        PRIMARY KEY,
    sequence       bigint      GENERATED BY DEFAULT AS IDENTITY,
    user_id        text        NOT NULL,
    content        text        NOT NULL,
    state          text        NOT NULL,
    answer         text        NULL,
    failure_reason text        NULL,
    accepted_at    timestamptz NOT NULL,
    claimed_at     timestamptz NULL,
    finished_at    timestamptz NULL,
    claimed_by     text        NULL,

    CONSTRAINT ck_messages_state
        CHECK (state IN ('Pending', 'Processing', 'Completed', 'Failed')),
    CONSTRAINT ck_messages_user_id_not_blank
        CHECK (length(btrim(user_id)) > 0),
    CONSTRAINT ck_messages_content_not_blank
        CHECK (length(btrim(content)) > 0)
);

-- The exclusivity invariant (FR-003). This is the feature, expressed as a constraint:
-- PostgreSQL refuses a second concurrent Processing row for the same user, so a claim
-- race is decided by the database rather than by application discipline.
CREATE UNIQUE INDEX IF NOT EXISTS ux_messages_active_per_user
    ON messages (user_id)
    WHERE state = 'Processing';

-- Serves both "next message for this user" and the sweeper's "users with pending work".
CREATE INDEX IF NOT EXISTS ix_messages_pending
    ON messages (user_id, sequence)
    WHERE state = 'Pending';

-- Serves the expiry scan.
CREATE INDEX IF NOT EXISTS ix_messages_processing_claimed_at
    ON messages (claimed_at)
    WHERE state = 'Processing';
